---
pip_install_packages:
  - name: docker

docker_users:
  - kazgrmruslan

redmine_image: redmine:latest
redmine_container_name: redmine
redmine_app_path: /opt/redmine
redmine_port: 80

redmine_domain: hexlet-tutorial.ru
redmine_db_host: rc1a-2um369d35ms7bgbf.mdb.yandexcloud.net
redmine_db_port: 6432
redmine_db_name: redmine
redmine_db_user: redmine
redmine_db_password: "{{ vault_redmine_db_password }}"
redmine_secret_key_base: "{{ vault_redmine_secret_key_base }}"
